// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMsi6tbABItvTJMPt-yS2vqGm0C03C_o8',
    appId: '1:1037162977977:web:ff3bc2f9ff9eebf1c9d968',
    messagingSenderId: '1037162977977',
    projectId: 'koc-18421-webs',
    authDomain: 'koc-18421-webs.firebaseapp.com',
    storageBucket: 'koc-18421-webs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDEfjVmrQT6_A-EK7gLgVZry78Tu8_S4',
    appId: '1:1037162977977:android:9a8ea49e2735ce9dc9d968',
    messagingSenderId: '1037162977977',
    projectId: 'koc-18421-webs',
    storageBucket: 'koc-18421-webs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZTKoDehrCzr0Zlwja6LnkExHsk17cx_A',
    appId: '1:1037162977977:ios:236505cd14562cb8c9d968',
    messagingSenderId: '1037162977977',
    projectId: 'koc-18421-webs',
    storageBucket: 'koc-18421-webs.firebasestorage.app',
    iosBundleId: 'com.example.kocCouncil18421',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZTKoDehrCzr0Zlwja6LnkExHsk17cx_A',
    appId: '1:1037162977977:ios:236505cd14562cb8c9d968',
    messagingSenderId: '1037162977977',
    projectId: 'koc-18421-webs',
    storageBucket: 'koc-18421-webs.firebasestorage.app',
    iosBundleId: 'com.example.kocCouncil18421',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMsi6tbABItvTJMPt-yS2vqGm0C03C_o8',
    appId: '1:1037162977977:web:a69182ea23e95affc9d968',
    messagingSenderId: '1037162977977',
    projectId: 'koc-18421-webs',
    authDomain: 'koc-18421-webs.firebaseapp.com',
    storageBucket: 'koc-18421-webs.firebasestorage.app',
  );
}
